### ISSUE TITLE
Raspberry Pi support?

### ISSUE THREAD

**Issue by A143718** [MycroftAI/enclosure-mark1#101]
Hi!

Would it be possible to run this on a raspberry PI oled display? Has anyone tried that?

Thanks,

Andres

**Comment by penrods** [comment]
This code is wirtten for the Arduino that is connected to the Mark 1's Raspberry Pi over a serial port.  I highly doubt this code is useful in any way for an OLED display -- that is a completely different beast.

**Comment by A143718** [comment]
Thanks for the reply!

**Comment by penrods** [comment]
No problem!
