### ISSUE TITLE
Bug Long mouth image string doesn't work

### ISSUE THREAD

**Issue by forslund** [MycroftAI/enclosure-mark1#104]
@JarbasAl originally reported that the [MycroftMouth::showIcon()](https://github.com/MycroftAI/enclosure-mark1/blob/master/lib/MycroftMouth/MycroftMouth.cpp#L177) method doesn't handle split icon strings correctly.

After debugging we found that the `$` sign indicating that a continuation message will be sent isn't stripped from the icon string generating a faulty code.

Additionally [the documentation](https://github.com/MycroftAI/enclosure-mark1/blob/master/protocols.txt) doesn't match the implementation. It states that the followup code should start with a $ instead of end with one.

A basic fix has been created in the [bugfix/large-image](https://github.com/MycroftAI/enclosure-mark1/commit/ac58a25a84dfb8ff9be88d83c3cc13e51327f369) branch

**Comment by JarbasAl** [comment]
fixed by #106
