### ISSUE TITLE
Introduce concept of `MycroftMatrix`

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/enclosure-mark1#25]
## Problem

To me it makes sense that we have two classes that represent the Neopixel rings and the LED matrix. Since the rings are only currently used as eyes I see the name acceptable. However, the matrix is used for both facial expressions and displaying various pieces of information such as the weather. Since the screen itself can only hold one thing on it at a time I was thinking we should probably have a class representing the matrix. @jdorleans mentioned that he did not want the mouth animations grouped with the weather which makes sense since they are handled differently. On the other hand, I think there should be some state representing that the weather is displayed rather than using the `NONE` state to retain the image drawn by the weather.
## Solution

I suggest that we have a MycroftMatrix class that holds both a MycroftMouth and a MycroftWeather. Then this MycroftMatrix class could hold a state pointing to either displaying a mouth or a weather screen.
### Is this necessary?

In the future there will be more screens such as calendar screen or a menu screen (in fact, I think we should also add a text screen to the matrix). Without a central system for handling these things the fragile mouth-centric state system will begin to show its age.

@isaacnward , @jdorleans , Any thoughts on this?

**Comment by highjinx411** [comment]
Hi.  I don't think this is a good idea.  The way I am reading this is every time a new skill wants to have a screen then they need to update this class.  That's no fun.  It starts small and eventually will get huge.  What I mean is creating a skill will have to do X number of things. You add this and it's X+1. Someone else comes along and adds something else.. It WILL get out of control and make it not fun at all to create a skill.  I have seen it happen all the time.  I have an idea.  You could have MycroftMatrix be the base class for the screen.  Mouth and Weather will inherit the properties from Matrix.  Matrix will contain the screen matrix and you could make it be a singleton with only one instance.  The other classes will have access to the screen but not have their own copy.. It also makes sense in OOP.  The weather and time classes **ARE A** type of matrix class.. Not the matrix class **HAS A** weather and time.  See what I am saying?  Let me know what you all think but yeah that's the way it should go.  I would like to do this actually.  I have been looking for something to do.

**Comment by penrods** [comment]
Moved to simply displaying sectional and full-screen graphics.  Writing Arduino code for each Skill isn't feasible.  Weather icons are not defined in Python and passed as a graphic to the Arduino.
